services:
  db:
    image: postgres:15
    container_name: invest_postgres
    restart: always
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: invest
      POSTGRES_DB: investcontrol
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
