"""add module_id to private_credit_assets

Revision ID: 34b551522a47
Revises: c225723d30b9
Create Date: 2025-07-08 20:00:21.738768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34b551522a47'
down_revision: Union[str, Sequence[str], None] = 'c225723d30b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movements', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'positions', 'private_credit_assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'positions', 'control_modules', ['module_id'], ['id'])
    op.add_column('private_credit_assets', sa.Column('module_id', sa.UUID(), nullable=True))
    op.alter_column('private_credit_assets', 'profitability_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.create_foreign_key(None, 'private_credit_assets', 'control_modules', ['module_id'], ['id'])
    op.alter_column('private_credit_categories', 'allocation_planned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('private_credit_categories', 'currency',
               existing_type=postgresql.ENUM('BRL', 'USD', 'EUR', name='currency_enum'),
               nullable=False)
    op.alter_column('private_credit_categories', 'module_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('private_credit_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('private_credit_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uix_category_name_module_id', 'private_credit_categories', ['name', 'module_id'])
    op.create_unique_constraint(None, 'private_credit_categories', ['id'])
    op.drop_constraint(op.f('fk_category_module_id'), 'private_credit_categories', type_='foreignkey')
    op.create_foreign_key(None, 'private_credit_categories', 'control_modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'private_credit_categories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_category_module_id'), 'private_credit_categories', 'control_modules', ['module_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'private_credit_categories', type_='unique')
    op.drop_constraint('uix_category_name_module_id', 'private_credit_categories', type_='unique')
    op.alter_column('private_credit_categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('private_credit_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('private_credit_categories', 'module_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('private_credit_categories', 'currency',
               existing_type=postgresql.ENUM('BRL', 'USD', 'EUR', name='currency_enum'),
               nullable=True)
    op.alter_column('private_credit_categories', 'allocation_planned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'private_credit_assets', type_='foreignkey')
    op.alter_column('private_credit_assets', 'profitability_percent',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.drop_column('private_credit_assets', 'module_id')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.alter_column('movements', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
