"""add unique constraint to categories

Revision ID: c61cea3d5a82
Revises: 8ad0af392e0a
Create Date: 2025-06-30 19:24:01.199429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61cea3d5a82'
down_revision: Union[str, Sequence[str], None] = '8ad0af392e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_category_name_module', 'categories', ['name', 'module'])
    op.create_unique_constraint(None, 'categories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint('uix_category_name_module', 'categories', type_='unique')
    # ### end Alembic commands ###
